TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------------------
# ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Optimization of db files using dbst (DEFAULT: NO)
# DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB_INSTALLS += check_update.db
DB_INSTALLS += ims_short.db
DB_INSTALLS += ims_long.db

#----------------------------------------------------
# Create and install (or just install)
# Archive files, templates, substitutions like this
ARCHIVE += ims_archive.tpl-arch

#----------------------------------------------------
# Create and install (or just install)
# Autosave request files, templates, substitutions like this
REQ     += ims_autosave.tpl-req


include $(TOP)/configure/RULES
#----------------------------------------
# ADD RULES AFTER THIS LINE

